# Generated by Django 5.2.14 on 2026-05-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professorsubjectassignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.professorprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='professorsubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
    ]
