# Generated by Django 5.2.14 on 2026-05-05 20:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorsubjectassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 5, 20, 35, 5, 828096, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='academics.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='professorsubjectassignment',
            unique_together={('professor', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject', 'academic_year', 'class_section')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'academic_year', 'section')},
        ),
        migrations.CreateModel(
            name='StudentFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_faces/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('embedding_data', models.JSONField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='academics.studentprofile')),
            ],
        ),
    ]
