# Generated by Django 5.2.14 on 2026-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
