# Generated by Django 5.2.14 on 2026-05-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_emaillog_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by_system',
            field=models.BooleanField(default=False),
        ),
    ]
